---
title: 'CKAN Series Part 5a: CKAN Installation - Package Requirements'
author: Ran Li
date: '2021-10-01'
slug: ckan-series-part-5a-ckan-installation-package-requirements
categories:
  - CKAN Series
tags:
  - CKAN
  - PostgreSQL 
  - GUI
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-01T11:45:46-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Now that we have our dev environment more or less set up, we can just rip the band aid off and try installing and playing around with CKAN. There are three installation protocols I found for CKAN on Ubuntu 20.04 one from [CKAN](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html), one from a [third party](https://musaamin.web.id/how-to-install-ckan-open-data-portal-ubuntu2004/) and one from a [CKAN-steward company (using Docker Compose)](https://tech.datopian.com/ckan/getting-started.html). We'll stick with the official CKAN documentation for an installation from source onto our Ubuntu VM. The installation will be covered in two blog posts the first focusing on CKAN package requirements then the second on actual installation/demo of CKAN.

This blog will focus on CKAN package requirements with the goal of keeping a detailed/reproducible log of versions used and getting a highly understanding of what each package actually does. The table below is an modified version of the one in the [CKAN documentation](https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html). I added a few packages as well as annotated it with emojis (📃) linking to my notes for each package.

+---------------------------+---------+------------------+------------------+
| Package                   | Version | CKAN Requirement | Purpose          |
+===========================+=========+==================+==================+
| Python [📄](#python)       | 3.8.10  | 3.6 or newer     | Backend          |
+---------------------------+---------+------------------+------------------+
| PostgreSQL [📄](#postgres) | 12.8    | 9.5 or newer     | Database         |
+---------------------------+---------+------------------+------------------+
| pgAdmin [📄](#pgAdmin)     |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| libpq                     |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| pip                       |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| python3-venv              |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| Git                       |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| GitHub Desktop            |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| Apache Solr               |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| Jetty                     |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| OpenJDK JDK               |         |                  |                  |
+---------------------------+---------+------------------+------------------+
| Redis                     |         |                  |                  |
+---------------------------+---------+------------------+------------------+
|                           |         |                  |                  |
+---------------------------+---------+------------------+------------------+

: click the 📃 emoji to jump to my notes describing this package

# Python {#python}

Python (named after the British TV show Monty Python) is a general-purpose, high-level programming language conceived in the late 1980's with version 0.9.0 released in 1991. General-purpose meaning can be used for a variety of tasks from web applications to data analysis. High-level meaning that Python is designed to be user-oriented allowing algorithms to be express in a more human readable manner via functions rather than other lower-level machine oriented languages (such as C++ or Java). Since then it become popular for implementing back ends to web applications using Django/Flask as well as more recently for data analysis/ML.

**CKAN's backend is built in Python.**

# PostgreSQL aka Postgres {#postgres}

Relational Databases is a set of tables (data tables with rows and columns) that contain information relation to other tables in the database via keys. SQL (Structured Query Language) is the standard language for interacting with relational databases. PostgreSQL is one implementation of relational databases and SQL. There are some technical points from which it differentiates from other SQL implementations but that is really beyond the scope my current expertise and this blog series.

But here are the main selling points of Postgres:

-   **OPEN SOURCED!** Do you see a theme through out this series in terms of things to consider when it comes to picking technologies to use? I am a huge fan of open sourced software; not only because of money but also popular open sourced software often have an active ecosystem of development and sharing of educational resources.

-   Rising in popularity compared to SQL Server

-   Supports many data types \*(documents, primitives, geometries.... even JSON, CSV, XML...)

Note to check Postgres is installed as 'psql' by apt; to check version use 'psql --version'

**CKAN's backend is built in Python.**

Note after installing you can check version and status by:

```{}
$ psql --version
$ sudo systemctl is-active postgresql
$ sudo systemctl is-enabled postgresql
$ sudo systemctl status postgresql
$ sudo pg_isready
```

# pgAdmin {#pgAdmin}

GUI (Graphical User interface) dramatically reduce the learning curve of most technologies compared to CLI (Command Line Interface). For this project I think the best approach is to use a GUI to initially set up and once we need to write queries from Django or stuff that needs automating we can go back CLI. pgAdmin is the most popular Postgres GUI; pgAdmin installation instructions on Linux can be found [here](https://www.pgadmin.org/download/pgadmin-4-apt/).

<https://www.tecmint.com/install-postgresql-and-pgadmin-in-ubuntu/>

<https://www.pgadmin.org/download/pgadmin-4-apt/>
