project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - blog.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

