project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - blog.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/ran-codes
      - icon: linkedin
        href: https://www.linkedin.com/in/ran-li-6b722718/
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/ran-li.bsky.social
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

