---
title: CKAN vs Next.js
author: Ran Li
date: '2021-10-04'
slug: ckan-vs-nextjs
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-04T09:52:30-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Met with some higher ups and the general consensus was to put CKAN on hold (because of how much of an investment it is to develop/maintain) and develop a more light-weight website. For that reason,I have been considering a Next.js implementation of React vs CKAN for the open data portal. Following reasons:

-   **CKAN may be over-engineering** as it the project we want to build is actually just a data portal doesn't need to be open to contributors. So a lot of the functionality (organizations/groups and user management) in CKAN is not necessary.

-   **CKAN educational resources is scarce:** As I was doing initial research into CKAN on of the things that stuck out was despite there being many example repositories of how people implemented CKAN, there were no online courses (udemy, Youtube...ETC). Which was concerning.

-   **CKAN deployment is not fun**. Whether you go the Docker route or Nginx route; production deployment would usually require three servers (Production, Development and User acceptance) which would not only cost quite a bit money but also likely require a full time engineer to maintain the CKAN instance and what over the devOps side of maintenance.

Instead of CKAN I thinking a Next.js implementation of a React application with a simple Non-SQL backend would work well. In fact one of the co-developers/stewards of CKAN [Datopian](https://www.datopian.com/) has been developing such a work flow and they packaged it as Portal.js. Here is their [explanation](https://portaljs.org/learn):

::: {style="padding-left: 15px;  background-color:rgb(220, 220, 220, 0.3);"}
Even still, there's a high learning curve before you can build a proper application. That's because you need to learn about Python, templating, data loading and so on. If you'd like to integrate content or rich visualizations things are even more complex.

**So, we need something simple but customizable.**

Think about how apps are created as a frontend developer. You create some files, write some code, load some data and then simply deploy it. We don't have to worry about Docker, Kubernetes, data storage, Postgres etc.
:::

After doing some research comparing a CKAN vs Next.js implementation of a data portal. Here are the following reason to go with the latter:

-   **Next.js has superior educational resources**: This is going to make development much faster. Moreover, since I have previous experience in building client-side applications these fundamental JS skills will translate much better in to a Next.js project rather than starting from scratch with CKAN (Python, Django...ETC).

-   **Easier deployment**: we can deploy via traditional CDN as we have with other project websites. This means fast turn around in development as well as **substantially lower server and man-hour cost (no need to dedicate personnel to manage AWS or Azure)**.

-   **Industry development**: There are several initiatives ([Portal.js](https://portaljs.org/) or [Open Data Campus](https://opendatacampus.com/)) to move the 'open data portal' scene out of the traditional CKAN/Django/Drupal /Postgres stack into a more modern tech stack composed of a React front-end with a flexible backend (you can really pick any database/structure which suits your needs). So it is quite confidence inspiring to see that others are going this route as well.

## Next Steps

Rapid prototyping of a proof of concept is the most important things. Developing a POC in a week or two demonstrates not only basic functionality but also speed of development of a particular tech stack. I will start with a crash course of Next.js then jump right into build a data portal POC.
