---
title: 'CKAN Series Part 4: Python IDE - PyCharm'
author: Ran Li
date: '2021-09-30'
slug: ckan-series-part-4-python-ide-pycharm
categories:
  - CKAN Series
  - Python
tags:
  - /uses
  - Pycharm
subtitle: ''
summary: ''
authors: []
lastmod: '2021-09-30T11:55:05-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

I will invest a bit of time familiarizing myself PyCharm and meaningful best-practices/settings/packages for productivity. From my experiences with Rstudio, I think time spent on learning IDE is a small investment for big long term return; if I had spent a few hours getting to know meaningful features and extensions of Rstudio early on in my R journey, I would have saved my self many headaches and many many hours of work. with that in mind there are two resource to learn from: PyCharm's own learning project as well as a setup for productivity [guide](https://www.youtube.com/watch?v=56bPIGf4us0&t=59s&ab_channel=TechWithTim) from TechWithTim.

## PyCharm Learning Project.

#### Onboarding

-   **Python Project**: any folder that contains any files in it. Can use PyCharm to open a folder like how VS Code opens folders.

-   **Run Configurations** can be selected to run each Python file; the main option here is which python interpreter to use (Python version).

-   **Run Toolbar**: is available after you select a run configuration. Short cut for various running actions (run, debug, profile and running with coverage).

-   **Debugger**: Similar to Rstudio you can insert breakpoints in your script and run a debugger (e.g. a micro-environment within the function to see function scoped variables to help debug)

-   **Auto-complete**: Similar to Rstudio, PyCharm will auto-complete function calls and variable calls. Sweet!

-   **Light-bulbs:** PyCharm adds light bulbs when you are at a line of code which it detects that improvements can be made (i guess refactoring for elegance or readability). You can press Alt Enter or click light bulb to see the suggest and decide to apply or not.

#### Editor basics

-   **Search** **for Actions**: press **Shift two times** or **Ctrl Shift A** to open search everything (IDE function, settings, file names .... ETC). You can set IDE settings here or preform actions such as case changes or line numbers...ETC.

-   :sparkles: **Expanding and shrinking code selection:** this is actually amazing and wish Rstudio has this. Ctrl+W to expand selection from caret, once for word, then keep pressing to go up in scale (e.g. caret \> word \> argument \> function \> just keeps going up code hierarchy). Then Ctrl+Shift+W to do the reverse (shrink).

-   **Comment or Un-comment line:** Ctrl+ /

-   **Moving code fragments**: Moving individual line use the IDE function 'Move Line Up/Down' to move entire chunks Ctrl+Shift+up/down

-   :sparkles:**Collapse:** For caret level: Ctrl+Minus to collapse, Ctrl+Equals to expand. For entire file: Ctrl+Shift+Minus to collapse, Ctrl+Shift+Equals to expand.

-   **Multiple Selection**: Alt+J to select next occurrences of symbol at caret. Alt+Shift+J to deselect last occurrences. Ctrl+Alt+Shift+J to select all occurrence; then type to replace.

#### Code Completion

-   **Basic completion**: Press enter for proposed completion, hit Ctrl+Space to activate basic completion explicitly.

-   **Tab Completion**: after activating basic completion you hit space to add the auto-complete or tab to replace the current symbol with the auto-complete

-   **F-string completion**: well i learned that {string} is actually called and *F-string.* Used it in R's glue and javascript back tick strings; very useful. Basic completion is implemented in F-strings in PyCharm.

#### Code Assistance

-   **Code format: Ctrl Alt L** to auto format code

-   **Parameter Info: Ctrl P** to see a method's signature (function's arguments).

-   **Quick Popups:** **Ctrl Q** to open up documentation popup (similar to Rstudio's '??'

-   **Editor coding assistance (errors)**: **F2** to go to next error in file. **Ctrl F1** to see description of error then **Alt Enter** to see suggested fixes.

#### Navigation

-   :sparkles: **Declaration and usages**: To open

-   :sparkles: **File Structure**: for large source files you can preview (similar to Rstudio's side menu) the file structure with **Ctrl F12**; this preview is interactive typing to filter. TO open a tool window with file structure press **Alt 7**.

-    **Find and replace in file:** this may be useful: searching for strings within a project across all files and replacing as needed (can customize scope). But long directions, better to refer to the lesson itself.

#### Run and debug

-   **Run Configuration**

    -   **Ctrl Shift F10** to run a python script. This will open the Run tool window at the bottom. **Shift Escape** to close this run window.

    -   Editing run config by using the **Edit Configurations** action

-   **Debugger Workflow:** Will come back to this as I become more familiar with function syntax in python. Note this [debugging in PyCharm tutorial](https://www.youtube.com/watch?v=sRGpvbhOhQs&t=2s&ab_channel=TechWithTim) from TechWithTim could also be a good reference.

## TechWithTim's PyCharm tutorial

-   **Refactoring Variable Names**: you can just use GUI by right clicking and selecting rename. This changes only within the scope of the currently selected variable.

-   Keyboard Shortcuts:

    -   **Ctrl F** to find

    -   **Ctrl D** to duplicate line

-   **✨Innate todo list:** Adding comments with the 'todo' keyword will automatically populate a to-do list in the Project tool window which links to do messages with file location and line numbers ETC. Seems very useful for small to do lists (sub commit level tasks!).

-   ✨**Surround with (Ctrl Alt T):** will create a list of common expressions (ifelse, try-except)...

## 
