---
title: 'React Crashcourse (Part 1): Introduction to React and ES6'
author: Ran Li
date: '2021-10-07'
slug: react-crashcourse-part-1
categories:
  - React
tags:
  - React
  - Course Notes
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-07T15:24:36-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Academind's Next.js crash course teaches how Next.js adds production features to React.js; so I will be taking a crash course in React.js as well. This series will serve as notes for [Academind's React course on Udemy](Next.js). Since I want to get working quickly I will go the concise route in this course: section 1 (Why React), section2 (ES6 JS refresher) and Section 29 (Summary/Core Features). I will cover these lessons in this React Crash course blog series.

**This first blog cover two things:**

-   **Introduce React**
-   **Give a refresher on next generation JS/ES6 syntax that is commonly used in React**

# React Introduction

### **Why use React?**

Mobile apps and desktop apps feel very "reactive": Thing happen instantly, you don't wait for new pages to load or actions to start.

Traditionally in web apps you click a link and wait for a new page to load. You click a button and wait for some action to complete. Cycle: Click -\> Request to Server -\> Server sends HTML -\> Render. This request and response cycle is what gives the unresponsive feel and is what we can break up with JS; React is a JS framework designed for to create responsive websites. Essentially, JS is an imperative approach (builds everything from scratch) React is a higher level 'declarative component focused approach' which makes making complex interfaces much easier. React builds Single-Page-Applications (SPAs).

React itself focuses on UI components and doesn't cover some features (such as Routing) therefore it needs some other third park packages. Angular/Vue.js while is component focused it has more features (such as Routing) thus is much more comprehensive; may be overkill for smaller projects.

### **React is all about "Components".**

While we can build complex website with many events and dynamic components with vannilla JS, HTML and CSS in a declartive manner it is very complex. Thats why we use React, it makes building complex, interactive and reactive UI simpler; by declaritive programming it makes the process much fast (allows you to focus on the logic without worrying about every single event) and less error prone. **React is all about "Components".**

Components are reusable building blocks (composed of HTML, CSS and JS) in your UI. In React we build these components and tell React how to compose them into the final UI. Components build on two programming concepts: 1) **Reusability** (don't repeat yourself) and 2) **Separation of Concerns** (Don't do too many things in one and the same place - function). Using components allows our codebase to be small and manageable; small spear units where each unit has a specific focus/concern split across multiple files making each concern easily maintainable.

### Setting up a React project

For this series I will be using Visual Studio Code as the IDE with the Prettier extension and node v14.17.0. Initialize a React act first navigate to a directory where you would like to create your project folder then initialize as follows.

    npx create-react-app project1-basic-react

Initialization takes a bit as Node will not only set up your folders structures for you but also download the required dependencies. To check everything is properly set up we can run our React app locally by navigating into our React project folder then use a node command

    cd project1-basic-react
    npm start

Note, this effect is a live-server. So any changes made to you React project will automatically be translated to what you see in the local port. Now let's take a look at what files are in our start React app:

-   package.json: details dependencies

-   ./node_modules: Node.js installs dependencies as per package.json into those folder. We don't touch this folder.

-   ./public: Includes the files need for React app: images, icons... ETC

-   ./src: this folder contains the code we will be editing.

Note, not all the default React app files are needed we remove a few see this [commit](https://github.com/rl627/udemy-react-js-academind/commit/d375f31232e0e761795359fbcded209c6f235681) for a minimized react application to start with.

### Analyzing a Standard React Project

``` {.javascript}
import ReactDOM from 'react-dom';

import './index.css';
import App from './App';

ReactDOM.render(<App />, document.getElementById('root'));
```

🦀When importing from js file or node_modules you don't need to and shouldn't add .js in the path.

Above is index.js. In React we write JS which direct React to build a UI. Index.js is essentially directions to how to make our root page (index.html). Note that there is some non-standard JS such as 1) the import CSS and 2) \`\<App/\>\` which looks like HTML code in JS; these only work because React transforms these before they get to browser. We import feature then call the ReactDom.render() function to render some JSX imported from App.js onto the 'root' id of index.html which can be found in /public.

Let's examine App.js

``` {.javascript}
function App() {
  return (
    <div>
      <h2>Let's get started!</h2>
    </div>
  );
}

export default App;
```

The HTML code is **JSX** a special implementation of HTML what works in JS due to React. App.js is a **React component:** a JS file which exports a JS function which returns JSX code which is use like an HTML element in index.js.

# Section 2: Next Gen JavaScript (ES6) Refresher

ES6 brings new syntax that make code more readable compared older versions of JS; the idea being write less, do more. React was built with ES6. Below are some key features of ES6 that are used in working with React.

### **let** & **const** replaces **var**

### **ES6 Arrow Functions**

Shorter syntax for writing function and keeps the scope of the this keyword

``` {.javascript}
function returnMe(name){
   return name;
}

const callMe = name => name
```

### Modules

In modern JS projects (particularly React), we split code across multiple JS files (called modules); this helps manage complexity by keeping each module focused on a certain task and scope. To access functionality in another file, you need to `export` (to make it available) and to `import` (to get access) statements. Exports can be named or default; React components are default exports from its parent module.

### Classes

Classes are blueprints for JS objects; they replace A class can have both properties and methods.

``` {.javascript}
class Person {
  name: "Max";
  printMyName = () => {console.log(this.name)}
}
```

You can instantiate an object based on a class using the 'new' keyword.

``` {.javascript}
const person = new Person();
person.printMyName();
```

We can use **inheritance** when using classes

``` {.javascript}
class Human {
  species = 'human';
}

class Person extends Human {
  name: "Max";
  printMyName = () => {console.log(this.name)}
}

const person = new Person();
console.log(person.species);
```

You can extend classes based on a parent class; note, that children classes new the super() keyword in its constructor. Classes are one of two ways to make components in React. Classes are just blueprints for JS objects and are very comparable to constructor function here inheritance is comparable to prototypes.

### Spread & Rest Operator (`…`)

Both use the same syntax of three dots. When we spread we use it to pull elements out of an array (=\> split array into a list of its elements) or pull the properties out of an object.

``` {.javascript}
// Pulling elements from an Array
const oldArray = [1, 2, 3];
const newArray = [...oldArray, 4, 5];

// Pulling properties out of an object
const oldObject = {
  name: 'Max'
};
const newObject = {
  ...oldObject,
  age: 28
}
```

**The spread operator is useful for cloning (creating immutable copies) of arrays and objects.** In JS there are two types of objects: 1) numbers, strings and Booleans are primitive types; meaning whenever you store a variable in another variable it will make a copy 2) Object and arrays are reference types; meaning, storing an array variable as another variable it will only stored as a reference (pointer to first).

### Destructuring

Destructuring allows you to easily access the values of arrays or objects and assign them to variables.

``` {.javascript}
// Destructuring an Array
const array = [1, 2, 3];
const [a, b] = array;
console.log(`{a}, {b}`); // prints '1, 2'

// Destructuring an Object
const myObj = {
  name: 'Max',
  age: 28
}
const {name} = myObj;
console.log(name); // prints 'Max'
console.log(age); //prints undefined
```

Destructuring is very useful when working with function arguments. For example:

``` {.javascript}
const printName = (personObj) => {
  console.log(personObj.name);
}
console.log({name: 'Max', age: 28});

// Refactor with destructuring
consy printName = ({name}) => {
  console.log(name)
}
console.log({name: 'Max', age: 28});
```

Same results, but with destructuring , we simply pull the `name` property and store it in a variable named `name` which we can use in the function body.

### Array Methods

This isn't ES6 but array methods will be used heavily. Here are the ones any JS developer should know well:

-   **map():** takes a function as an argument which is executed on each element in the array and **returns a real new array** (not pointer).

-   **find():** takes an conditional as an argument and **returns the value of the first element** in the array that satisfies the provided testing function.

-   **findIndex():** takes a testing function as an argument and **returns the index of the first element** in the array that satisfies the provided condition.

-   **filter():** takes a testing function as an argument and **creates a new array** with all elements that pass the test.

-   **reduce():** takes a reducer callback function as an argument and executes this reducer on each element of the array, passing the return value of the calculation on the preceding event. **The final result of running the reducer across all elements of the array is a single value**.

-   **concat():** takes an Array as a argument and merges the supplied Array with the original Array; the **result is a new merged array.**

-   **slice():** method **returns a shallow copy of a portion of an array** into a new array object selected from `start` to `end` (`end` not included) where `start` and `end` represent the index of items in that array. The original array will not be modified. (similar to dplyr)

-   **splice():** method changes the contents of an array by removing or replacing existing elements and/or adding new elements in place. It's like a mutable version of slice()
