---
title: 'Next.js Crashcourse: Page Routing '
author: Ran Li
date: '2021-10-05'
slug: next-js-crashcourse-page-routing
categories:
  - React
  - Next.js
tags:
  - React
  - Next.js
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-05T10:40:49-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

This will serve as my notes for the first part of [Academind's Next.js Crash Course](https://www.youtube.com/watch?v=MFuwkrseXVE&ab_channel=Academind). This section covers file routing system of Next.js including creating pages, dynamic pages and linking between pages.

### Project Initialization

Note I will be using Node.js version 14.17.0 with VS-code. The two extensions will be Prettier formatting and basic Tabnine for auto-completion. Git/GitHub for version control.

> npx create-next-app

Initialize a next.js react application in your directory. This creates four folders. /node_modules contains the JS dependencies. We won't touch this, Node takes care of this based on package.json. The other three folders are the important ones (pages being the most important).

-   pages: set up routing, which pages are in our folder.

-   public: holds public resources our page might use

-   styles: css

Lets remove some unneeded files for this lesson ([commit](https://github.com/rl627/next-js-course-academind/commit/f6f6670e01cf6fbeb00dbe52c6ab81993e4471ee)).

### Adding first Pages

The /pages folder defines the pages that make up our application. We will start with just \_app.js. Let say we want to build an website with three kinds of pages:

-   landing page

-   news page

-   news details, when we click news item we go to the full page for that item.

**Note in Next.With the exception of index.js, with the exception of index.js, the file name represents the path.** In the page folder we create three files. Index.js is the root page which will be served when a request form our base url. A news.js which will return when there is a request from url/news. Each of these JS files is a module which contains a react component (contains a function which returns HTML which is exported).

Lets start by populating titles in the news and index modules ([commit](https://github.com/rl627/next-js-course-academind/commit/24a2d788d3856b1aad6667cc2b627d05dc572e13)). We can now check this work by running a developmental server.

    npm run dev 

Note that there are two ways to handle pathing. First is as above, but **folder names also act as path segments, this is required for nested paths (url/news/something-important).** E.g. we can create a folder with the desire path name and having the js module within that folder name index.js. See the following for refactoring of news.js and addition of nested paths ([[commit]{.ul}](https://github.com/rl627/next-js-course-academind/commit/a2a35bf6aa677435d9e5239c818fbd9a7ff02261)).

### Adding dynamic pages

As stated before our news page would a list of news articles and clicking them would lead to a page with the actual content/news article for the selected news. Essentially this the same page over and over again or different news articles content; we would probably fetched these content from a database when a user visits this page and then display it on the screen. It's the same component but with different content.

So hardcoding the JS file identifier/name/path is not realistic as different article pages would have different path names. In this case we would want to create a dynamic page where the path segment can be dynamic. we do this by add to /pages/news a js file with square brackets

    /pages/news/[newsId].js

For now this page just returns the same HTML for all newsId but when we visit url/news/{anything_here} a dynamic site is generated. See [commit](https://github.com/rl627/next-js-course-academind/commit/929d0561e152c8543d5a041d1ce20811fe68805c).

Now that we have the pathing figured out, lets work on the content of our dynamic pages. First question is how can we extract the entered path value inside the component so we can for example fetch the correct news item form a database when a user visits this path. **Next.js provides us with a react hook (functions that let you 'hook into' React state from functional components) which allows us to extract the path value of a dynamic page.** Below, we import this hook useRouter() to return an object which is queried to get the router path!

    import { useRouter } from 'next/router';

    // our-domain.com/[newsId]

    function DetailPage() {
      const router = useRouter();

      console.log(router.query.newsId);

      return <h1>The Detail Page</h1>;
    }

    export default DetailPage;

Getting the path or newsId in our case opens up a world of possibilities for example we can send a request to a backend API to fetch news item with newsId. This will be covered later but for now the dynamic page + useRouter() hook is implemented in this [commit](https://github.com/rl627/next-js-course-academind/commit/ab89ece62d7e5522dfecee0a021fbce9e7f88d81).

### Navigation/Linking Pages

So far we have been entering URL's manually but users will use our news page ('/pages/news/index.js') to navigate to various news articles. This section introduces several fundamental React concepts including: 1) React Fragment 2) Links hook 3) State in React.

Lets first add a list in to news page. We utilize fragments to create list but note that if we just add a regular ordered list below our h1 tag the compiler throws an error. This is because **the JSX returned by React components must be wrapped in an enclosing tag** ([ref](https://www.youtube.com/watch?v=bHdh1T0-US4&ab_channel=Codevolution)). While we could just wrap our whole JSX with a div tag; this would introduce extra nodes in the DOM and when react components are rendered within some sensitive structure such as stylized grid, this extra div node would break things ([ref](https://blog.logrocket.com/react-fragments-an-overview/)). So best practice is to instead wrap the JSX with a React Fragment (which we need to import); this hook encloses our JSX but does not introduce extra nodes when rendered on the DOM.

Knowing this lets expand the JSX of our news page by adding a list of links via anchor tags ([commit](https://github.com/rl627/next-js-course-academind/commit/bd6facf3d25c9e346493bd4faba63fc8c1af55e6))

    function NewsPage() {
      return (
        <Fragment>
          <h1>The News Page</h1>
          <ul>
            <li>
              <a href="/news/nextjs-is-a-great-framework">
                NextJS Is a Great Framework
              </a>
            </li>
            <li>
              <a href="/news/something-else">
                Something Else
              </a>
            </li>
          </ul>
        </Fragment>
      );
    }

Note when we check this. It works, but also notice how every time we click a link the refresh icon briefly turns to a cross then returns to a refresh icon... this means the browser sent a request and got back a new HTML page. It works but the disadvantage is that we don't have a single page application (SPA).

we want to stay in that SPA because that allows us to preserve state across page and give the user a better reactive experience. That is the fundamentals of React where we build an interactive ui where we never send a request for a new HTML page but instead we update whats on the screen with React... thus staying in an SPA allows use to maintain state (Redux state, Context state, for example what user is logged in...).

Next.js provides us with pre-rendered HTML which is great for SEO and performance but if we use traditional anchor tags to navigate around a Next.js page then it is no long a SPA and we lose a lot of the benefits of React. THerefore in Next.js we need to make the link different using the Link hook which imported from next/links.Using it simple, we just replace anchor tags with Link; importantly, when <Link> is rendered as an <a> tag on the DOM so our styling still applies! ([commit](https://github.com/rl627/next-js-course-academind/commit/0fa2440cefd312fd1375ee4d6a735be9dc1366fd))

    import Link from 'next/link';
    import { Fragment } from 'react';

    // our-domain.com/news

    function NewsPage() {
      return (
        <Fragment>
          <h1>The News Page</h1>
          <ul>
            <li>
              <Link href="/news/next">NextJS Is a Great Framework</Link>
            </li>
            <li>Something Else</li>
          </ul>
        </Fragment>
      );
    }

    export default NewsPage;

Now when we click the first link we don't fetch a new HTML page instead we are on a SPA and the visible content is just re-rendered by React; this combines best of both worlds we have highly interactive reactive SPA where we can manage and store state across pages yet when users or search engine robots visit this page they be return the finished HTML results!

**Takeaway: for site-internal links with a Next.js application we want to use the Link component instead of anchor tags in order to maintain SPA.**

# 
